version: "3.9"
services:
  jupyter:
    image: jupyter/datascience-notebook:9b06df75e445
    ports:
      - 8888:8888
    volumes:
      - ./work:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - JUPYTER_TOKEN=12345
